//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double zoom_min {
            get {
                return ((double)(this["zoom_min"]));
            }
            set {
                this["zoom_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double zoom_max {
            get {
                return ((double)(this["zoom_max"]));
            }
            set {
                this["zoom_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double kV_max {
            get {
                return ((double)(this["kV_max"]));
            }
            set {
                this["kV_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double scan_d {
            get {
                return ((double)(this["scan_d"]));
            }
            set {
                this["scan_d"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double WD {
            get {
                return ((double)(this["WD"]));
            }
            set {
                this["WD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double kV {
            get {
                return ((double)(this["kV"]));
            }
            set {
                this["kV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double f_min {
            get {
                return ((double)(this["f_min"]));
            }
            set {
                this["f_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double p {
            get {
                return ((double)(this["p"]));
            }
            set {
                this["p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double I_scale_max {
            get {
                return ((double)(this["I_scale_max"]));
            }
            set {
                this["I_scale_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double filament {
            get {
                return ((double)(this["filament"]));
            }
            set {
                this["filament"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5400")]
        public int hv_raw_max {
            get {
                return ((int)(this["hv_raw_max"]));
            }
            set {
                this["hv_raw_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int fb_raw_max {
            get {
                return ((int)(this["fb_raw_max"]));
            }
            set {
                this["fb_raw_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Scanner_ISelect_Min {
            get {
                return ((int)(this["Scanner_ISelect_Min"]));
            }
            set {
                this["Scanner_ISelect_Min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Scanner_ISelect_Max {
            get {
                return ((int)(this["Scanner_ISelect_Max"]));
            }
            set {
                this["Scanner_ISelect_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double WD_offset_OBJ {
            get {
                return ((double)(this["WD_offset_OBJ"]));
            }
            set {
                this["WD_offset_OBJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double WD_offset_IML {
            get {
                return ((double)(this["WD_offset_IML"]));
            }
            set {
                this["WD_offset_IML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double q_max {
            get {
                return ((double)(this["q_max"]));
            }
            set {
                this["q_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000275829")]
        public double Coef_res_fine {
            get {
                return ((double)(this["Coef_res_fine"]));
            }
            set {
                this["Coef_res_fine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0455119")]
        public double Coef_res_course {
            get {
                return ((double)(this["Coef_res_course"]));
            }
            set {
                this["Coef_res_course"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int Focus_Max_res_fine {
            get {
                return ((int)(this["Focus_Max_res_fine"]));
            }
            set {
                this["Focus_Max_res_fine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Focus_Max_res_course {
            get {
                return ((int)(this["Focus_Max_res_course"]));
            }
            set {
                this["Focus_Max_res_course"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Focus_Min_res_fine {
            get {
                return ((int)(this["Focus_Min_res_fine"]));
            }
            set {
                this["Focus_Min_res_fine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Focus_Min_res_course {
            get {
                return ((int)(this["Focus_Min_res_course"]));
            }
            set {
                this["Focus_Min_res_course"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double IObj_WF {
            get {
                return ((double)(this["IObj_WF"]));
            }
            set {
                this["IObj_WF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000333333")]
        public double Coef_IML_fine {
            get {
                return ((double)(this["Coef_IML_fine"]));
            }
            set {
                this["Coef_IML_fine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double WD_real_IML {
            get {
                return ((double)(this["WD_real_IML"]));
            }
            set {
                this["WD_real_IML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int Zoom_Max_res {
            get {
                return ((int)(this["Zoom_Max_res"]));
            }
            set {
                this["Zoom_Max_res"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Zoom_Min_res {
            get {
                return ((int)(this["Zoom_Min_res"]));
            }
            set {
                this["Zoom_Min_res"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4095")]
        public int Focus_Max_IML_fine {
            get {
                return ((int)(this["Focus_Max_IML_fine"]));
            }
            set {
                this["Focus_Max_IML_fine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Focus_Min_IML_fine {
            get {
                return ((int)(this["Focus_Min_IML_fine"]));
            }
            set {
                this["Focus_Min_IML_fine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int Zoom_Max_IML {
            get {
                return ((int)(this["Zoom_Max_IML"]));
            }
            set {
                this["Zoom_Max_IML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Zoom_Min_IML {
            get {
                return ((int)(this["Zoom_Min_IML"]));
            }
            set {
                this["Zoom_Min_IML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double LogI_Min_Resolution {
            get {
                return ((double)(this["LogI_Min_Resolution"]));
            }
            set {
                this["LogI_Min_Resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double LogI_Max_Resolution {
            get {
                return ((double)(this["LogI_Max_Resolution"]));
            }
            set {
                this["LogI_Max_Resolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double LogI_Min_WideField {
            get {
                return ((double)(this["LogI_Min_WideField"]));
            }
            set {
                this["LogI_Min_WideField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double LogI_Max_WideField {
            get {
                return ((double)(this["LogI_Max_WideField"]));
            }
            set {
                this["LogI_Max_WideField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double LogI_Min_Field {
            get {
                return ((double)(this["LogI_Min_Field"]));
            }
            set {
                this["LogI_Min_Field"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double LogI_Max_Field {
            get {
                return ((double)(this["LogI_Max_Field"]));
            }
            set {
                this["LogI_Max_Field"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double LogI_Min_Rokveld {
            get {
                return ((double)(this["LogI_Min_Rokveld"]));
            }
            set {
                this["LogI_Min_Rokveld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double LogI_Max_Rokveld {
            get {
                return ((double)(this["LogI_Max_Rokveld"]));
            }
            set {
                this["LogI_Max_Rokveld"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public double vf_max {
            get {
                return ((double)(this["vf_max"]));
            }
            set {
                this["vf_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double vf_min {
            get {
                return ((double)(this["vf_min"]));
            }
            set {
                this["vf_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal num_stig_min {
            get {
                return ((decimal)(this["num_stig_min"]));
            }
            set {
                this["num_stig_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal num_stig_max {
            get {
                return ((decimal)(this["num_stig_max"]));
            }
            set {
                this["num_stig_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal num_gain_min {
            get {
                return ((decimal)(this["num_gain_min"]));
            }
            set {
                this["num_gain_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal num_gain_max {
            get {
                return ((decimal)(this["num_gain_max"]));
            }
            set {
                this["num_gain_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal num_obj_min {
            get {
                return ((decimal)(this["num_obj_min"]));
            }
            set {
                this["num_obj_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal num_obj_max {
            get {
                return ((decimal)(this["num_obj_max"]));
            }
            set {
                this["num_obj_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal num_iml_min {
            get {
                return ((decimal)(this["num_iml_min"]));
            }
            set {
                this["num_iml_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal num_iml_max {
            get {
                return ((decimal)(this["num_iml_max"]));
            }
            set {
                this["num_iml_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal num_gunshift_min {
            get {
                return ((decimal)(this["num_gunshift_min"]));
            }
            set {
                this["num_gunshift_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal num_gunshift_max {
            get {
                return ((decimal)(this["num_gunshift_max"]));
            }
            set {
                this["num_gunshift_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal num_guntilt_min {
            get {
                return ((decimal)(this["num_guntilt_min"]));
            }
            set {
                this["num_guntilt_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal num_guntilt_max {
            get {
                return ((decimal)(this["num_guntilt_max"]));
            }
            set {
                this["num_guntilt_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Setting {
            get {
                return ((double)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal stage_rot {
            get {
                return ((decimal)(this["stage_rot"]));
            }
            set {
                this["stage_rot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal stage_hys {
            get {
                return ((decimal)(this["stage_hys"]));
            }
            set {
                this["stage_hys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double WD_offset_Scanner {
            get {
                return ((double)(this["WD_offset_Scanner"]));
            }
            set {
                this["WD_offset_Scanner"] = value;
            }
        }
    }
}
